### ISSUE TITLE
[FR] Move docker repo name to a secret/variable

### ISSUE THREAD

**Issue by radicand** [docker-mailserver/docker-mailserver-new#17]
# Feature Request

## Context

Currently in our workflow files we have hardcoded `docker.io/mailserver/docker-mailserver` for the repo name. In order to continue testing workflow/push-related actions safely in private repos, this should move to become a variable so the forked owner can push images to their own username/org/image in Dockerhub (or elsewhere) without needing to modify the workflow files ad-hoc.

### Is your Feature Request related to a Problem?

N/A

### Describe the Solution you'd like

Creation of a new repository secret `DOCKER_REPONAME` that we set to `docker.io/mailserver/docker-mailserver`, followed by an update to the push-related workflows to leverage this, removing the hardcoded `docker.io/mailserver/docker-mailserver` reference. We do not need to modify anything beyond the GHA workflows.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

I will create a PR upon creation of the new repo secret.

### Alternatives you've considered

N/A

### Who will that Feature be useful to?

Anyone who wants to fork the repo.

### What have you done already?

N/A

**Comment by aendeavor** [comment]
I have added a secret called `DOCKER_REPOSITORY`. But wait - we must keep in mind not to run into the same problem that we first encountered during the errors with the PR workflow! We cannot use this secret for our PR workflow since we're running this workflow against forked repositories.

I have provided a PR for this. All images that stay local now have the name `mailserver-testing` while the secret will expand to `docker.io/mailserver/docker-mailserver`.
